# test/Makefile

check:
	$(MAKE) -C format-code check
	$(MAKE) -C format-macro check
	$(MAKE) -C replace-across check

clean:
	$(MAKE) -C format-code clean
	$(MAKE) -C format-macro clean
	$(MAKE) -C replace-across clean

# EOF
