#!/usr/bin/perl -w
# enqueue a playlist.txt file in a running alsaplay instance

use strict;

if (scalar(@ARGV) != 1) {
  die("usage: $0 playlist.txt\n");
}

my $debug = 0;

my $playlist = $ARGV[0];

# read $playlist into @filenames
my @filenames = ();
open(IN, "<$playlist") or die("cannot read $playlist: $!\n");
my $line;
while (defined($line = <IN>)) {
  # chomp
  $line =~ s/[\r\n]+$//;
  
  # remove comments
  $line =~ s/\#.*//;
  
  # skip blank lines
  if ($line =~ m/^\s*$/) {
    next;
  }
  
  push @filenames, ($line);
}
close(IN) or die;

# construct a command line
my @cmd = ("alsaplayer", "--session", "0", "--replace", @filenames);
if ($debug) {
  for my $s (@cmd) {
    print("$s\n");
  }
}

(system(@cmd)==0) || die("alsaplayer failed with code $?\n");

# EOF
