#!/bin/sh
# back up a directory using rsync

if [ "x$1" = "x" ]; then
  echo "usage: $0 <sourcedir> [<destdir>]"
  echo ""
  echo "If <destdir> is omitted, then the source directory must have"
  echo "a 'backup' symlink in it."
  echo ""
  echo "The <destdir> can be <machine>:<dest> to make a remote copy."
  exit 2
fi

SRCDIR="$1"
if echo "$SRCDIR" | grep '/$' >/dev/null; then
  echo "The directory argument should not end with a slash."
  exit 2
fi

if [ "x$2" = "x" ]; then
  DESTDIR=`readlink "$1/backup"`
  if [ $? -ne 0 ]; then
    echo "error: No <destdir> provided and there is no symlink called: $1/backup"
    exit 2
  fi
else
  DESTDIR="$2"
fi

exec runecho rsync --verbose --archive --delete \
  --exclude="data-coverity" \
  --exclude="*.o" \
  --exclude="*.class" \
  --exclude="*.i" \
  --exclude="*.ii" \
  --exclude="*.exe" \
  --exclude="/bld" \
  --exclude="/dist" \
  --exclude="/.m2" \
  --exclude="/opt" \
  --exclude="backup.tar.gz" \
  --exclude="/.ccache" \
  --exclude="/.cache" \
  --exclude="/lib" \
  "$SRCDIR/" "$DESTDIR"

# EOF
