#!/bin/sh
# bk annotate, but line numbers only

if [ "x$1" = "x" ]; then
  echo "usage: $0 file"
  exit 2
fi

file="$1"

# start with the info about the current version
bk log -r+ "$1"

# for some reason bk normally leaves a bunch of empty columns,
# so use 'cut' to strip that crap out
bk annotate -An "$file" | cut -b1-6,14-

# EOF
