#!/bin/sh

echo "building, output to make.out ..."
(make clean && make) >make.out 2>&1 || exit

echo "running testsuite, output to testsuite.out ..."
make testsuite >testsuite.out 2>&1 || exit

echo "doing bk pull, push, pull, x3, output to push.out ..."
bk-pull-push-pull-all-three >push.out 2>&1 || exit

echo "success"
runecho tail push.out
