#!/bin/sh

echo "building, output to make.out ..."
(make clean && make) >make.out 2>&1 || exit

echo "running testsuite, output to testsuite.out ..."
make testsuite >testsuite.out 2>&1 || exit

echo "doing bk pull, push, pull, output to push.out ..."
bk-pull-push-pull >push.out 2>&1 || exit

echo "success"
exec bk-revname
