#!/bin/sh
# scp a file from a remote repo to here

if [ "$2" = "" ]; then
  echo "usage: $0 host:repo filename"
  exit 2
fi

src="$1"
shift

while [ "$1" != "" ]; do
  fname="$1"
  shift

  if [ -w "$fname" ]; then
    echo "$fname already writable; bailing"
    exit 2
  elif [ -r "$fname" ]; then
    runecho bk edit "$fname" || exit
  fi

  runecho scp "$src/$fname" "$fname" || exit
done

# EOF
