#!/bin/sh
# display the source of a script
# (or info on binaries)

if [ "$1" = "" ]; then
  echo "usage: $0 script-name"
  exit
fi

# find source
loc=`which "$1"`
if [ "$?" != "0" ]; then
  echo "failed to locate $1"
  exit
fi

# show file info
ls -ld "$loc"

# if that's a link, show info for linked file
if [ -L "$loc" ]; then
  ls -ldL "$loc"
fi

# check file type (-L means dereference links)
filetype=`file -L $loc`
case "$filetype" in
  *text*)
    # is a text file: cat it to screen
    cat $loc
    ;;

  *executable*)
    # is a binary: show type and ldd info
    echo "$filetype"
    ldd "$loc"
    ;;
    
  *)
    echo "$filetype";
    ;;
esac
