#!/bin/sh
# display the source of a script

if [ "$1" = "" ]; then
  echo "usage: $0 script-name"
  exit
fi

name=$1

# find source
loc=`which "$1"`
if [ "$?" != "0" ]; then
  echo "failed to locate $1"
  exit
fi;

# check file type
if file $loc | grep "text" >/dev/null; then
  # is a text file; cat it to screen
  cat $loc
else
  # is not a text file
  echo "$loc is not a text file"
fi
