#!/usr/bin/env python
# convert CSV input into mediawiki table markup output

# example output:
#
#   {| border="1"
#   | a || b || c
#   |-
#   | d || e || f
#   |-
#   | g || h || i
#   |}

import csv                   # csv.reader
import sys                   # sys.argv

class Error(Exception):
  """A condition to be treated as an error."""
  pass

# True to make the first row a title row.
firstRowTitle = 0

try:

  if len(sys.argv) < 2:
    print("usage: [-title] "+sys.argv[0]+" input.csv")
    sys.exit(2)

  if sys.argv[1] == "-title":
    firstRowTitle = 1
    inputFname = sys.argv[2]
  else:
    inputFname = sys.argv[1]

  with open(inputFname, "rt") as csvfile:
    reader = csv.reader(csvfile)

    print("{| border=\"1\"");

    for fields in reader:
      if firstRowTitle:
        print("! "+(" !! ".join(fields)))
      else:
        print("| "+(" || ".join(fields)))
      break

    for fields in reader:
      print("|-")

      # Bug: If one of the fields contains wiki metacharacters
      # like "||" itself, this will not escape them.
      print("| "+(" || ".join(fields)))

    print("|}")

except Error as e:
  print("Error: "+e.args[0])
  sys.exit(2)

except IOError as e:
  if e.filename:
    print("Error: "+e.filename+": "+e.strerror)
  else:
    print("Error: "+e.strerror)
  sys.exit(2)

# EOF
