#!/bin/sh
# wrapper around cvs to remember what I did when; useful for knowing
# which version of a repository I was using before a 'cvs update'
# that broke everything..

realcvs=$HOME/opt/cvs-1.11.18/bin/cvs
if [ ! -x $realcvs ]; then
  realcvs=/usr/bin/cvs
  if [ ! -x $realcvs ]; then
    realcvs=/usr/local/bin/cvs
    if [ ! -x $realcvs ]; then
      echo 'scripts/cvs: cannot find real cvs'
      exit 4
    fi
  fi
fi

if [ "$1" = "-n" -o \
     "$1" = "log" ]; then
  # assume we're doing something like "cvs -n update", which
  # doesn't need to be added to the log
  exec $realcvs "$@"
fi

if echo "$*" | grep -- --help >/dev/null; then
  # we're asking cvs for help; don't log this either
  exec $realcvs "$@"
fi

echo `date`" in "`pwd`": cvs $*" >> $HOME/.cvslog
exec $realcvs "$@"
