#! /bin/csh -f
# script to download (via http) a file, using -source

if ("$1" == "") then
  echo usage: $0 url [filename]
  exit
endif

set fname = $2
if ("$fname" == "") then
  set fname = `echo "$1" | sed 's%.*/%%'`
endif
echo downloading to $fname

lynx -source "$1" > $fname
