#!/bin/sh
# search for a library symbol in a set of libraries

if [ "$2" = "" ]; then
  echo "usage: $0 sym-to-find files..."
  exit
fi

sym=$1
shift

while [ "$1" != "" ]; do
  #echo "$1"
  nm $1 2>/dev/null | grep -i $sym | sed "s#^#$1:#"
  shift
done


