#!/bin/sh
# apply various UI changes to a default mozilla distribution

# the diffs below were intiially based on build 2001101108

# I poked around for some simple xml command-line tools to do
# the transformations in a structured way, but didn't find
# anything suitable (didn't look all that hard..)

if [ "$1" = "" ]; then
  echo "usage: $0 mozilla-install-dir [jarfile]"
  exit 0
fi

# bail on error
set -e

moz="$1"
tmp=~/tmp/fix-moz-$$

# link the plugins
if [ ! -f $moz/plugins/rpnp.so ]; then
  echo "linking plugins"
  ln -s ~/dist/plugins/* $moz/plugins
fi


# begin modifying a jar file
explode_jar() {
  mkdir $tmp
  cd $tmp
  cp $moz/chrome/$1.jar /tmp/$1.jar.orig || exit
  jar xvf $moz/chrome/$1.jar || exit
}


# finish modifying a jar file
repackage_jar() {
  cd $tmp
  if [ `ls | wc -l` != 1 ]; then
    echo "unexpected number of directories in jar file"
    exit 2
  fi
  jar cvfM $1.jar * || exit

  # replace old one
  cp $1.jar $moz/chrome

  # clean up
  cd ..
  rm -rf $tmp
}


if [ "$2" != "" ]; then
  # just edit one jar file
  explode_jar "$2"
  echo "press enter when done editing..."
  read
  repackage_jar "$2"
  exit 0
fi


# ------------------------ comm.jar --------------------------
explode_jar comm

cd content/navigator

cat <<EOF
Starting editor on navigatorOverlay.xul:
  Rearrange the menu bar, putting Bookmarks and Go first,
  search for "<!-- Menu -->".
  Also, delete the "Send Page..." option from the File menu (if present).
EOF
emacsclient navigatorOverlay.xul

cat <<EOF
Starting editor on navigator.xul:
  Remove forward, reload, stop buttons; search for "forward-button"
    and delete the three buttons.
  Disable urlbar popup: search for "urlbar" and change
    alwaysOpenPopup to "false".
  Remove component bar: search for "component-bar" and delete the line.
EOF
emacsclient navigator.xul

cd ../communicator

cat <<EOF
Starting editor on contentAreaContextOverlay.xul:
  Move the navigation entries to the top of the context menu;
  search for "contentAreaContextMenu" and move Open below Navigation.
EOF
emacsclient contentAreaContextOverlay.xul

cat <<EOF
Starting editor on platformCommunicatorOverlay.xul:
  Delete the keybindings for key_close, key_closeWindow and key_quit.
EOF
emacsclient platformCommunicatorOverlay.xul

repackage_jar comm


# ------------------------ en-US.jar --------------------------
explode_jar en-US

cd locale/en-US/navigator

cat <<EOF
Starting editor on navigator-title.dtd:
  Remove the build-id string from the two places it occurs.
EOF
emacsclient navigator-title.dtd

repackage_jar en-US


# -------------- end ----------------
echo "All done.  Remember to grab the preferences bar from xulplanet.com."
