#!/bin/sh
# print the git graph in a somewhat readable format

# The output is pretty wide, so a wide terminal is best.

# Fields:
#   %h: Commit hash, usually 7 digits.
#   %ad: Author date, respecting git date configuration.
#   %an: Author name.
#   %s: Commit subject, usually first line of message.
#
# See also:
#   https://git-scm.com/docs/pretty-formats

exec git log --graph --pretty=format:'%h %ad %an %s'

# EOF
