#!/bin/sh
# export a single cset to a patch file

if [ "$1" = "" ]; then
  echo "usage: $0 revnum"
  exit 2
fi

rev="$1"

if [ -d .git ]; then
  # get parent
  parents=`git log -n 1 --format=format:%P $1`
  if [ x = "x$parents" ]; then
    echo "failed to get parents of $rev"
  fi
  parent=`echo $parents | awk '{ print $1 }'`
  if [ x = "x$parent" ]; then
    echo "failed to get parent of $rev"
  fi

  # get diff
  echo git diff "$parent..$rev" \> "changeset-$rev.patch"
  git diff "$parent..$rev" > "changeset-$rev.patch"

  exit
fi

# get the parent of the revision
parent=`bk prs -h -r$rev -d:PARENT:`
if [ x = x$parent ]; then
  echo "failed to get parent of $rev"
  exit 2
fi

echo bk export -tpatch "-r$parent..$rev" \> "changeset-$rev.patch"
bk export -tpatch "-r$parent..$rev" > "changeset-$rev.patch"
exit

# EOF
