#!/bin/sh
# grep all source code

if [ "x$1" = "x" ]; then
  echo "usage: $0 [<grep options>] <grep-style regexp>"
  exit 2
fi

# git ls-files is passed the name of the repo root directory, which
# causes it to print all files in the repo, and as paths relative to
# the working directory.  Without that, it only prints names of files
# in the working directory and below.
#
# grep options:
#   -n: Print line numbers.
#   -H: Print file name even if only one passed.
git ls-files $(git rev-parse --show-toplevel) | xargsn grep -n -H "$@"

# EOF
