#!/usr/bin/perl -w
# make an ascii histogram

use strict;

# map from line contents to occurrence frequency
my %lineToFreq = ();

my $line;
while ($line = <STDIN>) {
  chomp($line);

  incHashElt(\%lineToFreq, $line);
}

# unique line contents
my @lines = keys(%lineToFreq);

# sort by increasing occurrence frequency
@lines = sort {
  my $c = $lineToFreq{$a} <=> $lineToFreq{$b};
  if ($c == 0) {
    $c = $a cmp $b;     # break ties alphabetically
  }
  return $c;
} @lines;

# print
for $line (@lines) {
  my $ct = $lineToFreq{$line};
  printf("%8d %s\n", $ct, $line);
}

sub incHashElt {
  my ($hash, $elt) = @_;

  my $cur = $hash->{$elt};
  if (defined($cur)) {
    $hash->{$elt} = $cur + 1;
  }
  else {
    $hash->{$elt} = 1;
  }
}

# EOF
