#!/bin/sh
# re-indent JSON on stdin, writing to stdout

# look for a repo
classfile=objs/linux64/classes/com/coverity/json/JSONTest.class
if [ -f $HOME/prevent-gilroy/$classfile ]; then
  repo=$HOME/prevent-gilroy
elif [ -f $HOME/enc/prevent-gilroy/$classfile ]; then
  repo=$HOME/enc/prevent-gilroy
else
  echo "failed to find a repo with JSONTest" 1>&2
  exit 2
fi

# temporary files
tmpin=/tmp/indent-json.tmpin.$$
tmpout=/tmp/indent-json.tmpout.$$
onExit()
{
  rm -f $tmpin
  rm -f $tmpout
}
trap onExit EXIT

# grab all the input and store it in a file
cat > $tmpin

# run JSONTest to parse it
java -cp $repo/objs/linux64/classes com.coverity.json.JSONTest $tmpin ' ' > $tmpout

# Strip out the first line that says how many results there were.
tail -n +2 $tmpout

# EOF
