#!/usr/bin/env python3
"""Print stdin as a JSON string."""

import json                            # dumps
import sys                             # stdin

print(json.dumps(sys.stdin.read()), end="")

# EOF
