#!/usr/bin/perl -w
# compute integer portion of log base 10 of input numbers

use strict;

my $n;
while (defined($n = <STDIN>)) {
  chomp($n);
  print(int(log10($n) + 0.5) . "\n");
}


# from perlfunc man page
sub log10 {
  my ($n) = @_;
  return log($n)/log(10);
}


# EOF
