#!/usr/bin/perl -w
# compute integer portion of log base 2 of input numbers

use strict;

my $n;
while (defined($n = <STDIN>)) {
  chomp($n);
  print(int(log2($n) + 0.5) . "\n");
}


# from perlfunc man page
sub log2 {
  my ($n) = @_;
  return log($n)/log(2);
}


# EOF
