#!/bin/sh
# cp -al all my important files to a separate directory

# bail on error
set -e

# like ls -a, except don't print . or ..
listall() {
  #/bin/ls -a | grep -v '^\.\{1,2\}$'
  
  # gnu option: -A means -a except no . or ..
  /bin/ls -A
}

mkdir ~/backup
cd ~
cp -al `listall | egrep -vw \.loki\|News\|backup\|bak\|bin\|bld\|dist\|distleetch\|lib\|madrone\|mp3\|nsmail\|share\|tmp\|vmware\|wrk` ~/backup

# remove some settings dirs which take more space than I want
cd ~/backup
rm -rf .mozilla/default/Cache .mozilla/*/*/Cache \
       .netscape/cache .opera/cache* .vslick .gftp/cache \
       .kde/share/apps/krn

mkdir ~/backup/wrk
cd ~/wrk
cp -al `listall | egrep -vw cs164\|cplr\|harmonia\|safec\|sftpd\|gmp-3.1` ~/backup/wrk

mkdir ~/backup/wrk/cs164
cd ~/wrk/cs164
cp -al `listall | egrep -vw cool\|cool-cvs` ~/backup/wrk/cs164

mkdir ~/backup/wrk/cplr
cd ~/wrk/cplr
cp -al `listall | egrep -vw parsgen\|harmonia\|ast` ~/backup/wrk/cplr
