#!/bin/sh
# cp -al all my important files to a separate directory

# bail on error
set -e

# like ls -a, except don't print . or ..
listall() {
  #/bin/ls -a | grep -v '^\.\{1,2\}$'
  
  # gnu option: -A means -a except no . or ..
  /bin/ls -A
}

echo "hardlinking lots of stuff..."

mkdir ~/backup
cd ~
cp -al `listall | egrep -vw '\.loki|News|backup|bak|bin|bld|dist|dist2|dl|distleetch|emu|ex|lib|madrone|mp3|nsmail|share|tmp|vmware|wrk|old.*|wine|opt|mail'` ~/backup

# remove some settings dirs which take more space than I want
cd ~/backup
rm -rf .mozilla/default/Cache .mozilla/*/*/Cache \
       .netscape/cache .opera/cache* .vslick .gftp/cache .kde

# directories in doc of stuff I can retrieve again
cd ~/backup/doc
rm -rf hardware man software movies papers pix rfc

# directories already backed up on previous CDs
cd ~/backup/doc/sch
rm -rf fa00 fa98 fa99 sp00 sp01 sp99

mkdir ~/backup/wrk
cd ~/wrk
cp -al `listall | egrep -vw 'cs164|cplr|harmonia|safec|sftpd|gmp-3.1|learn|gta3|inactive|wedding'` ~/backup/wrk

mkdir ~/backup/wrk/cplr
cd ~/wrk/cplr
cp -al `listall | egrep -vw 'parsgen|harmonia|ast|smbase|elkhound|elsa|cc_qual|cqual|papers|verifier'` ~/backup/wrk/cplr

# copy 'mail', compressed
echo "compressing mail..."
cd ~/backup
cp -a ~/mail .
cd mail
gzip *
