#!/bin/sh
# given a list of image filenames, make an HTML index of them,
# assuming that thumbnail versions are in thumb/

while [ "$1" != "" ]; do
  base=`basename $1`
  echo '<a href="'"$1"'"><img src="thumb/'"$base"'"></a>'
  shift
done
