#!/bin/sh
# get a manpage and write it to a file

if [ "$1" = "" ]; then
  echo "usage: $0 manpage [section]"
  exit
fi

# I always forget this and get terminal garbage in the file
export LANG=C

man $2 $1 | rmctlh > ~/doc/man/$1.man
