#! /bin/csh -V -E -f

# check arguments
if ("a$3" == "a") then
  echo "Usage: monitor command zero_msg one_msg [interval]"
  exit 1
endif

# set default interval if not set
if ("a$4" == "a") then
  set interval = 60
else
  set interval = $4
endif

# set default
set current = 0
unset noglob

while (1)
  set newval = `$1`
  if ($current < 1)
    if ($newval > 0)
      set current = 1
      echo $3 >> ~/log
    endif
  endif

  if ($current > 0)
    if ($newval < 1)
      set current = 0
      echo $2 >> ~/log
    endif
  endif

  sleep $interval
end
