#!/usr/bin/env python
# given the name of a CSV file exported from a Pivotal project,
# print HTML links to all stories to stdout

import csv                   # csv.reader
import sys                   # sys.argv

class Error(Exception):
  """A condition to be treated as an error."""
  pass

# https://wiki.python.org/moin/EscapingHtml
#
# do not escape quotes because I am trying to match the links
# with what is in my design doc
htmlEscapeTable = {
  "&": "&amp;",
  #'"': "&quot;",
  #"'": "&apos;",
  ">": "&gt;",
  "<": "&lt;",
}

def htmlEscape(text):
  """Escape 'text' for use in HTML text and attributes."""
  return "".join(htmlEscapeTable.get(c,c) for c in text)

def checkColumn(header, index, label):
  if header[index] != label:
    raise Error("Expected column "+str(index)+" to be '"+label+
                "', not '"+header[index]+"'")

try:

  if len(sys.argv) != 2:
    print("usage: "+sys.argv[0]+" input.csv")
    sys.exit(2)

  inputFname = sys.argv[1]

  with open(inputFname, "rt") as csvfile:
    reader = csv.reader(csvfile)

    idIndex = 0
    storyIndex = 1
    storyTypeIndex = 6
    currentStateIndex = 8
    urlIndex = 14      # 2014-03-01: they changed it from 15

    header = reader.next()
    checkColumn(header, idIndex, "Id")
    checkColumn(header, storyIndex, "Story")
    checkColumn(header, storyTypeIndex, "Story Type")
    checkColumn(header, currentStateIndex, "Current State")
    checkColumn(header, urlIndex, "URL")
    #print(", ".join(header))

    for row in reader:
      id = row[idIndex]
      story = row[storyIndex]
      storyType = row[storyTypeIndex]
      currentState = row[currentStateIndex]
      url = row[urlIndex]

      # When I extract CSV from Pivotal, the links use HTTP, whereas
      # I always access it with HTTPS so I want that instead.
      url = url.replace("http://", "https://")

      # Accepted tasks should be marked "done".
      if currentState == "accepted":
        story = story + " (DONE)";

      # Ignore stories in the icebox (unscheduled).
      if currentState == "unscheduled":
        continue

      # Also ignore bugs
      if storyType == "bug":
        continue

      print("<a href=\""+htmlEscape(url)+"\">Pivotal "+id+": "+htmlEscape(story)+"</a>")

except Error as e:
  print("Error: "+e.args[0])
  sys.exit(2)


# EOF
