#! /bin/csh -f
# grep for a process

if ( "$1" == "" ) then
  echo usage: $0 string-to-grep-processes-for "[ps-to-ignore]"
  exit
endif

if ( "$2" == "") then
  /bin/ps -ef | grep $1 | grep -v grep | grep -v $0
else
  /bin/ps -ef | grep $1 | grep -v grep | grep -v $0 | grep -v $2
endif


