#!/bin/sh
# remove given targets, then make them

MAKE="${MAKE:-make}"

if [ "x$1" = "x" ]; then
  echo "usage: $0 target [targets ...] [VAR=VALUE ...]"
  echo "Removes the first target, then invokes '$MAKE' with all arguments."
  exit 2
fi

echo rm -f "$1"
rm -f "$1" || exit

echo $MAKE "$@"
exec $MAKE "$@"

# EOF
