#!/usr/bin/perl -w
# remove the nth line from stdin that has a given text

if (@ARGV < 2) {
  print("usage: $0 text n < input > output\n");
  print("  modifies the nth line, counting from 0, that contains <text>\n");
  print("  the modification is to remove <text>\n");
  exit(0);
}

($text, $n) = @ARGV;

#print("text=$text n=$n\n");
#exit(0);


while ($line = <STDIN>) {
  if ($line =~ /$text/) {
    if ($n-- == 0) {
      $line =~ s/$text//;     # remove that text
    }
  }
  print($line);
}


