#!/bin/sh
# rename a set of files by applying a line filter to
# each name which yields the name to rename-to

# check usage
if [ "$2" = "" ]; then
  echo "usage: $0 [-n] filter-program files..."
  echo "Option '-n' means to only print the commands without running them."
  exit
fi

# True if we are only printing the commands.
dryRun=false
if [ "x$1" = "x-n" ]; then
  dryRun=true
  echo "Dry run mode active; printing commands only."
  shift
fi

# grab program name
filter="$1"
echo "filter program is $filter"
shift

# process filenames
for fname in "$@" ; do
  # generate new name
  newname=`echo "$fname" | $filter`

  if [ "$newname" = "$fname" ]; then
    echo "skipping $fname -- new name is identical"
  else
    echo mv -i "$fname" "$newname"
    if $dryRun; then
      true
    else
      # rename and try not to clobber anything
      # if it fails, stop immediately
      mv -i "$fname" "$newname" || exit
    fi
  fi
done



