#!/bin/sh
# run a program some number of times

if [ "$2" = "" ]; then
  echo "usage: $0 times-to-run command [args...]"
  exit 2
fi

n="$1"
i=0
shift

while [ $i -lt $n ]; do
  echo "$i: $*"
  "$@"

  i=`expr $i + 1`
done

# EOF
