#!/usr/bin/perl -w
# run a command with specified printenv environment

use strict 'subs';

if (@ARGV < 2) {
  print("usage: $0 env-file cmd [arg [args ...]]\n");
  exit(2);
}

$envfile = $ARGV[0];
shift @ARGV;

%ENV = ();

if (!open(IN, "<$envfile")) {
  die("cannot read $envfile: $!\n");
}
while (defined($line = <IN>)) {
  chomp($line);
  ($name, $var) = ($line =~ m/^([^=]+)=(.*)$/);
  if (!defined($var)) {
    print STDERR ("malformed line: $line\n");
    exit(2);
  }
  $ENV{$name} = $var;
}
close(IN) or die;

exec(@ARGV);
die("$ARGV[0]: $!\n");

# EOF
