#!/bin/sh
# run a program, saving the command line and stderr to a log file

echo "---------------------------------------------------" >>$HOME/log/runlog.log
echo `date`": runlog-logerr:" "$@" >>$HOME/log/runlog.log

exec "$@" 2>>$HOME/log/runlog.log

# EOF
