#! /bin/csh -f
# just print my arguments

set i = 0
while ( "$i" <= "$#argv" )
  if ( "$i" == "0") then
    # tcsh is broken accessing argv with variable??
    echo "argv[0] = '$0'"
  else
    echo "argv[${i}] = '${argv[$i]}'"
  endif
  @ i++
end
