#!/bin/sh
# start xclock the way I like
                  
# try to use my modified version with AM/PM indicators
xclock=xclock-ampm
if ! which $xclock >/dev/null 2>&1; then
  xclock=xclock
fi

kstart --type Dock -window xclock $xclock -digital -update 1 -geometry 191x22+0-0
sleep 1

# move it where I want it since kde doesn't respect geometry
id=`xwininfo -name $xclock | grep "Window id" | awk '{ print $4 }'`
id=$id
if [ "$id" = "" ]; then
  echo "Couldn't find the right window id"
  exit 2
fi

# 'movewin' is a program I wrote (~/wrk/learn/x/movewin.cc)
#movewin $id -llcorner -move 0 1002 -size 200 38 -lower
movewin $id -lower
