#!/bin/sh
# start xbiff the way I like

kstart --type Dock -window xbiff myxbiff
perl -e 'select(undef, undef, undef, 0.25);'

# move it where I want it since kde doesn't respect geometry
id=`xwininfo -name xbiff-nobeep | grep "Window id" | awk '{ print $4 }'`
id=$id
if [ "$id" = "" ]; then
  echo "Couldn't find the right window id"
  exit 2
fi

# 'movewin' is a program I wrote (~/wrk/learn/x/movewin.cc)
movewin $id -size 48 48 -move 200 992
