#!/bin/sh
# start the cpu-monitor in a tiny xterm on a remote machine

if [ "$1" = "" ]; then
  echo "usage: $0 hostname"
  exit 2
fi

# use 'xload' title since that's already one KDE knows to not
# put decorations on
xterm -title xload -geometry 53x1+0-13 +sb -e ssh $1 cpu-monitor
