#!/bin/sh
# all the things I do as 'scott' when I boot my machine

echo "connectivity monitor..."
monitor-connectivity >> ~/doc/logs/connectivity-log 2>&1 &

#echo "email fetcher..."
#start-fetchmail

#echo "news monitor..."
#check-news-loop &

if [ `hostname` == "leetch" ]; then
  echo "mixer settings..."
  aumix -L
fi

