#!/bin/sh
# all the things I do when I start an X session (for kde)

# this finds the window id of the given window title
grab_id() {
  # clever way to sleep for less than a second
  perl -e 'select(undef, undef, undef, 0.25);'

  id=`xwininfo -name "$1" | grep "Window id" | awk '{ print $4 }'`
  id=$id
  if [ "$id" = "" ]; then
    echo "Couldn't find the right window id"
    exit 2
  fi
}

# assume I'm running this from my first xterm
stitle wrk

cd $HOME

xset b off

# turn off that damned screen blanking!
xset s off

# off!  off!
xset -dpms

# .xinitrc is taking care of this?
#xmodmap-make.caps.another.ctrl

# xclock does not seem to respect the -fn command line argument any more!
#start-xclock

start-cpu-monitor
#start-xbiff
start-logwin

# mp3
xterm -geometry 80x24+0-32 -title mp3 -e sh -c 'stitle mp3; console-renice -15 $$; cd $HOME/mp3; exec bash' &
grab_id mp3
if [ -f /etc/slack8 ]; then
  movewin $id -move 0 645
else
  movewin $id -move 0 640
fi

# pine
#  xterm -title pine -fn "-misc-fixed-medium-r-normal-*-15-*-*-*-*-*-iso8859-1" -e /bin/sh -c 'mypine; exec bash' &
#  grab_id pine
#  if [ -f /etc/slack8 ]; then
#    movewin $id -move 530 537 -size 739 430
#  else
#    movewin $id -move 535 537 -size 739 430
#  fi

# cpu-monitor, which ends up in the wrong position when the MWM-style
# window decorations are used..
#grab_id cpu-monitor
#movewin $id -llcorner -move 0 992 -size 250 10

#kmix

#killall artsd

# it turns out klipper is the horrible thing which brings up that
# window when I select a URL text
#
# and in later versions of KDE it can be disabled by right-clicking
# on its icon in the system tray
#echo "Killing klipper..."
#psgrep klipper | awk '{ print $1 }' | xargs kill
#killall klipper

# see if the truetype font server is working
#  if xlsfonts | grep -i girls >/dev/null; then
#    # ok
#    true
#  else
#    echo "the truetype font server isn't working.."
#  fi
