#!/bin/sh
# just grab whatever is on stdin and append it to a logfile

set -e

secs=`date +%s`
fn=$HOME/tmp/$secs.log
echo "args: $*" >> $fn
exec cat >> $fn
#cat >> $fn

# who is calling this?
#echo "my pid is $$" >> $fn
#/home/scott/scripts/pssall >> $fn

