#! /bin/sh
# swap two files

if [ "$2" = "" ]; then
  echo "usage: $0 file1 file2"
  echo "this script swaps the two filenames"
  exit 2
fi

tempname="swaptmpname"
while [ -e "$tempname" ]; do
  # just keep prepending 'a' until it's unique
  tempname="a$tempname"
done

mv "$1" "$tempname" || exit
mv "$2" "$1" || exit
mv "$tempname" "$2" || exit
