#!/bin/sh
# switch which mouse we're using

if [ "$1" = "" ]; then
  echo "usage: switchmouse [ps2|serial]"
  exit
else
  sudo /sbin/switchmouse $*
fi

# since it's an important variable also, report which
# display(s) are active
grep disp /etc/XF86Config
