#!/bin/sh
# script to tar and bzip a directory

if [ "$1" == "" ]; then
  echo "usage: $0 directory-name"
  echo "  writes directory-name.tar.bz2 into current directory"
  exit
fi

# I often screw up and put a trailing slash in the name
# (by using tcsh filename completion); this fixes it
d=`echo $1 | sed 's#/$##'`

tar cvf - $d | bzip2 > $d.tar.bz2
