#!/bin/sh
# run rosetta-from-hg and confirm output against expected

if [ "$1" = "" ]; then
  echo "usage: $0 hg-repo"
  exit 2
fi

hgRepo="$1"

if [ ! -d "ros-$hgRepo" ]; then
  echo "ros-$hgRepo should already exist"
  exit 2
fi

if [ -d ros ]; then
  runecho rm -rf ros
fi
runecho rosetta-from-hg.pl "$hgRepo" ros || exit

if runecho diff --recursive --brief "ros-$hgRepo" ros; then
  runecho rm -rf ros
else
  exit $?
fi

# EOF
